kind: pipeline

steps:
- name: compile
  image: microsoft/dotnet:sdk
  commands:
    - sh build.sh
- name: build-image
  image: plugins/docker
  settings:
    username: rajmanyapatekar
    password: d021c2ec-16ee-42cc-a346-8508c900a17d
    repo: rajmanyapatekar/dotnetcore-container
    dockerfile: Web/Dockerfile
